package de.morphyum.advent.day4;

import de.morphyum.advent.helper.Solver;

public class Main {

	static String input = "kvvfl kvvfl olud wjqsqa olud frc\r\n" + "slhm rdfm yxb rsobyt rdfm\r\n"
			+ "pib wzfr xyoakcu zoapeze rtdxt rikc jyeps wdyo hawr xyoakcu hawr\r\n"
			+ "ismtq qwoi kzt ktgzoc gnxblp dzfayil ftfx asscba ionxi dzfayil qwoi\r\n"
			+ "dzuhys kfekxe nvdhdtj hzusdy xzhehgc dhtvdnj oxwlvef\r\n"
			+ "gxg qahl aaipx tkmckn hcsuhy jsudcmy kcefhpn kiasaj tkmckn\r\n" + "roan kqnztj edc zpjwb\r\n"
			+ "yzc roc qrygby rsvts nyijgwr xnpqz\r\n" + "jqgj hhgtw tmychia whkm vvxoq tfbzpe ska ldjmvmo\r\n"
			+ "nyeeg omn geyen ngyee rcjt rjuxh\r\n" + "qpq udci tnp fdfk kffd eyzvmg ufppf wfuodj toamfn tkze jzsb\r\n"
			+ "rrcgxyp rbufd tfjmok vpyhej hcnz ftkojm\r\n" + "jnmomfc jnmomfc bkluz izn ovvm flsch bkluz\r\n"
			+ "odisl hzwv hiasrhi hez ihihsra qpbmi ltwjj iknkwxf nbdtq gbo\r\n" + "gjtszl gjtszl fruo fruo\r\n"
			+ "rdapv gaik cqboix sxnizhh uxmpali jdd usqnz advrp dze\r\n"
			+ "flooz flooz qad tcrq yze bnoijff qpqu vup hyagwll\r\n" + "lnazok dze foi tqwjsk hpx qcql euzpj mwfrk\r\n"
			+ "ilb fmviby ivybmf gtx xtg\r\n" + "rpauuu timere gyg wcolt ireetm safi\r\n"
			+ "croe szwmq bbhd lciird vhcci pdax\r\n" + "hnc ykswt qqqmei goe bri wmyai hnc qpgqc pberqf bzs\r\n"
			+ "hsnrb wdvh iezzrq iezzrq rdbmpta iezzrq kemnptg alkjnp wymmz\r\n"
			+ "ngw don ddvyds nlhkoa aaf gptumum ugtpmmu\r\n" + "vmccke qbpag kvf kvf tgrfghb kvf bhpd sglgx\r\n"
			+ "obomgk bkcgo yso ttft vbw ckl wjgk\r\n" + "fli qvw zhin dfpgfjb udsin nihz ovr tiewo\r\n"
			+ "tgmzmph hauzieo jmg tdbtl lvfr qpaayq qapaqy ausioeu jun piygx\r\n"
			+ "jkp guqrnx asdqmxf vmfvtqb tloqgyo ioix gajowri tmek ilc puhipb\r\n"
			+ "uycn zxqm znft ayal znacus kvcyd ekv qqfpnh\r\n" + "fqghur xtbtdd ztjrylr bpuikb ziyk\r\n"
			+ "rvakn uqbl ozitpdh uqbl dsej xehj\r\n" + "laxp haz jyd xnkrb ijldth woy xapl iqgg alpx gnupa ukptmmh\r\n"
			+ "dyiy dyiy ihb qcyxr\r\n" + "wbwkd hdwu zvgkn hdwu wjc sakwhn zxujdo npllzp uyr uyr\r\n"
			+ "fxczpmn cininu akcxs ggslxr riyxe ojisxe\r\n" + "ppbch sampq dnct afikor dnct edsqy pnzyzmc afikor\r\n"
			+ "jnvygtn hijqjxl vsd jnvygtn nqcqv zns odq gkboxrv kolnq wrvd\r\n" + "mroq mroq flsbu flsbu\r\n"
			+ "fyshor xvpaunj qmktlo xoce wkiyfu ukcl srndc ugwylwm ozcwdw mtqcste kpokr\r\n"
			+ "cfh cxjvx cfh cfh uewshh\r\n" + "bpspbap bpspbap fquj mxmn bwls iirhvuk dmpkyt exrn mxmn\r\n"
			+ "tvyvzk ezszod ntxr xtnr och\r\n" + "knfxhy kbnyl knfxhy xhkssx lxru uprh nkxpbx oodolxr tpvyf\r\n"
			+ "nblmysu iwoffs upgof tyagwf aan vovji ajk ywzq oyfi sfulz\r\n"
			+ "aushzkm lcaeki mkuzsah ynxvte rsntd refk pcm\r\n" + "mgguob gobmug dzenpty gmogbu\r\n"
			+ "yvq eepof rgnree nerger fpb stfrln ernger\r\n"
			+ "hrgkbl mzwvswk rsrsbk ieru holco pajvvn ztgsr qkyp fyeg owpcmoj\r\n"
			+ "fowda gmsqdca yugj mcrroxv mqcbojd fjnqfji qdfsc jqs\r\n"
			+ "qnc rvjfz vvxk sjd xrma ucdjvq sbw zydyt dfzww\r\n"
			+ "ocajazv cozaajv tqunkla udwf ecnnmbz lsakqg bki njnda zsdu ccfqw rxpc\r\n"
			+ "qqm qdfya qxyx qmq qfday uqnfttt\r\n" + "rnbirb iapor qet iapor hxkhz dfvzig pedl ybyb\r\n"
			+ "mkgamxg xkniv meb hbzmxjn dhbj zhbxjmn hdjb\r\n" + "ilteux pyutyfx mau lrr bacak\r\n"
			+ "sjjonmn dbbbgs crxyuu jztstgd ezb uiabyaa\r\n"
			+ "tra fle ufzlvf nnaw kec hiwnnlj tei wld iyt syk hjdczb\r\n"
			+ "qmd jtlud dgh dbanock fzp dsjgqru wwvo jwvxwgv xlemfij jcacd\r\n"
			+ "rpkx oxesil snazcgx fly miiyc ikmtmp oefyyn egbw\r\n"
			+ "ypfpeu wldnyd acchppb yqwcaw wldnyd turbz megci nbgxq xkc ypfpeu\r\n" + "iqqv iqqv neui iqqv\r\n"
			+ "ypsxm icqyup zyetrwq nbisrv\r\n"
			+ "viommi toszx dpueq eyy cunjou ffcjc jaeez djefra pxvkj liudlig yye\r\n"
			+ "fhnacbg jghchh ghjhhc iue hwqmo\r\n" + "vbjw lpn cizba ltnsfpz tzoweml irewlc uzckhpd mszal obd\r\n"
			+ "yeos utxkft hflxkfe fxczge qpgigkc ksgr vuumql vhlvv\r\n"
			+ "xzmkv xzmkv krecdi klpem jsbu nwcmik emfzxf cjmpgnj\r\n"
			+ "vtkjo pmiv zou gxo qdiyxsf hwyinjk jhkgf rjq\r\n" + "dyuoc ywiyvch irfgl ywiyvch fxb fxb\r\n"
			+ "tuz onhr syu rqya abkaf bcfx mbknex juwoor zmksl\r\n" + "oheg spjorx ksdy vwtq fxz phvtazk tcze lrxg\r\n"
			+ "hew lbup botaj ltr jpd\r\n" + "dxgc tzinkej gnz hxvvub adsqmc dxgc asgpp rqbdcra goy pmamdua bhiacva\r\n"
			+ "xqv ygb kihxqz vyv pjcny vmyvsdv cgsi nfyx\r\n"
			+ "tqga ssshrw ndq qlbvwh huyd pxbgj qbxk dkkbf jxy chsobw pph\r\n" + "hxl iwph iwph xnr otifm ljhre\r\n"
			+ "zlgvpd kapxpoc dve rklk ogh hgnp rbrmc zzkz hhmcx aklmo\r\n" + "sar gfor nkf hek nkf aql shc aql\r\n"
			+ "dtcrw kfjzcjx qyhi bldson whwdayo mqtgt xhqzp ttqmg\r\n"
			+ "omspdml isze jdl nvwo qrkm wztfg ssfgyh dryj jhp unsmty\r\n"
			+ "jxt cszylng ifht ixtuna azoi xutqlv jtx tjx\r\n" + "usgm azuayp fgkby ezpyq jqwl ezofj\r\n"
			+ "tnhvil nrvg moyrpqs sldx qymoff megflxh pyhqwms xmdw\r\n" + "zomy zcquwnv lzx bvcna yods mjp dgsez\r\n"
			+ "blklyf xokd gpit tiysj yrwfhm tofx\r\n" + "dtig vhdp omuj vhpd\r\n"
			+ "fogwxim qvdwig emdiv jvhl euwbzkg xvxb hwmqo ujdmlp epmykj\r\n" + "sjxll sjxll pedvgb sjxll\r\n"
			+ "drvay gtzhgtx yrt okz nqf\r\n" + "haxfazn pvkovwb pgu tgshw mxcjf pbe nwoymzc mxcjf pbe hydwy jradcr\r\n"
			+ "prjsloa ahylvj okbsj qbdcdjt pmfo pagyoeg vkmhjzt khzmjvt opfm xfrji gyjqyel\r\n"
			+ "lzypt jdbtrad ogr jdbtrad heink\r\n" + "rcoucuq gdxewa rcoucuq whlw zhhm rcoucuq azaqohe mzyli rdvaf\r\n"
			+ "yuag ebcf yuag nsotg qqzuxr jfmao vyucw wmoye\r\n"
			+ "qwvk xemm hgqrr wyxkpp tojndm xlvzypw jus bgnu bgnu nklfwhs\r\n"
			+ "daqi knenmku ccm xkiuy vkexsbc kvvdagx umopitw yaocnx yoakqql mllmsp\r\n"
			+ "mrxgl gywit mfopia ncnsvw vdxek axuiot rsejua nei prndudz mnu\r\n" + "egqn gaa qgen urs mix zbn rhn\r\n"
			+ "ewharq aihy udkdaob kgrdd kgrdd kugbjtj fcef llqb pduxaq wcexmm\r\n"
			+ "dwtiw nelq hppad algxgf gcc upou akm efnb mxmhrud\r\n" + "yxqaa ups okbhgt iet qns tqn rnjqxgp\r\n"
			+ "npmhdm cgds ldexvr typi jyivoqk zkgq vfyxu xgfo\r\n"
			+ "dkwnmr umm dkwnmr okpjw wqx jpztebl eqsib dkwnmr\r\n"
			+ "dxbild wpbup evscivq dxbild dxbild geqp ojfbpl jshvqej\r\n"
			+ "cxdntxs csfocjd pyy tuhws teb boyloz xfw scxh pxhonky\r\n" + "lteucke xrgwy hszgzu hnyrcvb\r\n"
			+ "pfgsgwg dxzh fworek qbstod\r\n" + "usemcrf psczxu gcjtr brls\r\n"
			+ "hjol efxczux bqdn gvrnpey yyoqse gbam ndzyj lbwb bhzn unsezg\r\n"
			+ "bapw xifz blupk qqdk bofvqpp wnbuwyt rnwocu lzwgtt zucag pov\r\n" + "xkre lqvd juf lqvd xio xyg xyg\r\n"
			+ "tzdao ztheib aymcf aorg iyawrch hetcxa iyawrch czdymc ccv\r\n" + "ucgl azlppu jvxqlj pest\r\n"
			+ "dvwlw fuuy mnhmm okrp ualnqlm uyuznba fzyejk yaq crl ctprp\r\n"
			+ "odfq knox mkbcku pxucmuf lpjpol phl\r\n"
			+ "ixongh hfs ruorbd auy qyssl kykwcix aytsm rlj aytsm duq segpqhk\r\n"
			+ "izufsk wedpzh podjkor eamo vqvev ifnz podjkor xrnuqe\r\n" + "twyfps bmdbgtu qye qkwjms\r\n"
			+ "wlav htym vhsnu cocphsj mdsuq vhsnu jflgmrp\r\n" + "opajag itwjhfu purnnvk opajag\r\n"
			+ "hpkopqp vnj aialpt lzrkzfs nwucez nwuezc\r\n" + "mcx hzcjxq zbxr dsx tpknx fva\r\n"
			+ "rlvgm xrejsvn ghawxb efyos xty wdzdgh olahbtn rga efyos vhtm nsr\r\n"
			+ "cni mbab qtgeiow ulttn rckc kmiaju jvbq emyvpew cdlxldn ulttn brhkprx\r\n"
			+ "eykpffp rapik qki fhjgdyu tome ehjuy bibjk htxd vexvag\r\n"
			+ "wrk dpxt gwkuiov gbkif ike gbkif pcd wpj toywyf qzsa aol\r\n" + "yqwzh uujn ujun ujnu\r\n"
			+ "srs ralwxrz yxvvmgp sjhbhk waasid cqtxoxf whcladv jkmaq khjbsh dlavcwh\r\n"
			+ "mdvsjh xaj etvxlsy fxgiy rgjesel rlegesj ptriz ebdyhkp kugxm dxv egljser\r\n"
			+ "lhehwrs mqevb ygmv gri izop qgb ivm\r\n" + "loqqam alojlwg hgen hbyw qlwpun loqqam worgnwk kope\r\n"
			+ "phozre todsknr todsknr ibj mvllsar\r\n"
			+ "wuripy ruwlfbh wukbkey qhq iishw tvtvci xawvxc vxacwx hsiwi ogq\r\n"
			+ "xryq vxwupqa zhqex aquxpwv bnvxrba dtbxki\r\n" + "yvvwh zvsm vqskhp vqskhp ggqqlw bpn wbuv\r\n"
			+ "kqz tdy goqwge ygn jgd\r\n" + "szjjhdk zkpoo nxexz ebicc\r\n" + "wzuemcj oyd qupulju iaakzmt vzkvz\r\n"
			+ "nppahov umm wpzev wxkgfxd owgekp bhhb bbhh dgviiw kdfgxwx wryb\r\n"
			+ "bnc rhes lmbuhhy kwbefga bnc rtxnvz bnc\r\n" + "ani mggxf mcoixh zdd nai hbhzl mes bdpqr\r\n"
			+ "mjn uinoty jjegvze bjgqg yhqsxbt coj obylb hddude xqi rhfbhha alood\r\n"
			+ "cbjzj drmihy tfkrhsd nuhav hihzx bvblqpl tdd szmp gjgfv box\r\n" + "uumhdxd cmwgyf vepr rwqdkj exwk\r\n"
			+ "hwvr ydvw bqefu kghes gvbhp awms iqsqes khgse\r\n"
			+ "mrey jqfw fwvzhps komj dayvs fbui zmtd cofn mrey\r\n"
			+ "dsjds fdpx irjj usndok qcctsvf fgk wvg txwxcl dxs llp zyilwtq\r\n" + "xmkelgk fdukc cye legkxkm wwly\r\n"
			+ "enlny eynln cccku brkz dpof mwfoxcd yftmnqh wpebvyc\r\n" + "ggdn jnysl dsacffw ukj hdae cmzxku\r\n"
			+ "uqhm gcachmn kxndfrl htmfis jfnajz fiqiypr kekho kekho ndcw ckrndub dejfna\r\n"
			+ "keazuq ertql rauwl keazuq obmh rauwl ksrotm\r\n" + "jppp poigqhv repfsje grjk xwkyuh pkx ayzcj hoxzv\r\n"
			+ "yhjw pcuyad icie icie icie hwcsuy wcd yihjh jnrxs\r\n" + "gaug ivvx ceb xujonak hbtfkeb ttciml cctoz\r\n"
			+ "dggyyi dggyyi gqlyumf yasu fwdfa cbb nncn verhq\r\n"
			+ "rhgcw gpcyct kiuhbg kiuhbg gpcyct jlmleo nhumm\r\n" + "wulxxu jyjek hclcp ogob viex wiqcupq\r\n"
			+ "tthu nxgzpid kcnj mss ukapgkp nnc bxjocv qwxs oejwsif aywqtu brahkb\r\n" + "dtde bgvb smu vbbg zhlu\r\n"
			+ "lyo nwjjmep ldbok wgxhto wwuh qfgjknk wnsl\r\n" + "lleyr onha hkwulbm jfg\r\n"
			+ "bybjwd uoxvbh mvj iqfpnxs bybjwd zqtszp wvc lbazjr zkzenja cev\r\n"
			+ "rbuyyr divtslq yuqmyt ajyveb smxsjb nlk tzqhq ims fewg wpjhr gqh\r\n"
			+ "kpewfd beq klilis klisli eeezut\r\n" + "euqh hueq ldoo crqurv lvrwh tmaewp oodl\r\n"
			+ "bqi lzrf jyhvxfh bqi jyhvxfh nbztd lwpdn cuzi\r\n" + "srjylou phavzjd wost uxkaq byh sluryoj\r\n"
			+ "ihrdk bcegkpq nygrs qbcq wyjg dvzme pgzhjl vibg kvv\r\n" + "ijsx iedemek ktlz gtga tbal lbki gtga\r\n"
			+ "vmiaxn kefig kefig vngxz\r\n" + "vrdmfvi qts vlvhq vlvhq dihmq\r\n"
			+ "cfz dyrz zlw qnt vok fwvahg skshbqf hbwozdc ntana jdb uflp\r\n"
			+ "rimbj bxemw sfps krtk umta vnk ewmbx nrlje ymrtqrz mxewb kjxunbt\r\n" + "egnuti ozat eltl ngueti\r\n"
			+ "qtcwoxq rmaf qtcwoxq qtcwoxq\r\n" + "zws gcoa pydruw qsrk lrkybdf ugr wkrxoj nyvf vitwn\r\n"
			+ "tmr hhd dojid zwrj bhsim righ keqlep flzunou\r\n" + "lwoquvy acjowxk tqudk oenvioh nyavyl\r\n"
			+ "rgh dfhgyke iff cpxhuz hui koe iff hui dmukrei\r\n" + "bjiumig lcbmbgh vleipx sfawua rnf\r\n"
			+ "gftfh qwb tfdroe xbno qhgofm vqfoe mux\r\n"
			+ "ljdrr gyfggai iun nju xrucbis mhrcrh fukr obvuqc whlalfe xrucbis nju\r\n"
			+ "nxjmjr egqwg arllu xqaahri lzc ivt uhsti\r\n" + "sqiepba rcmts kvesv nvp\r\n"
			+ "tiksw tiksw rjni gbhvzm ctbq zuqfyvz\r\n" + "ibsnm kfka aoqigwo sqouih rxz\r\n"
			+ "jmymq lxio adtmk umyu sxvzquq bporqnb heol fow\r\n"
			+ "mepa eckq rqviawv dkqoei ifmngpp jiava rtklseu\r\n"
			+ "yuycd jiufjci yuycd uowg yuycd udq izkicbr csxobh\r\n"
			+ "nwu tfsjavb rruoxbn oepcov elxf rruoxbn rruoxbn azglwth jcjm ksqiqpv\r\n"
			+ "dthfwip zqnwa zqnwa zqnwa\r\n" + "gso wruece ufl crgnlxv vllsm dpyfm wpa ctxko\r\n"
			+ "wvpze seodz lpq lpq pmtp wsxs ffppx\r\n"
			+ "yfxquj phvjn rtwieq rtwieq kgxztyu vbjvkc prqqd lyzmdo ojbrt ojbrt qiqjz\r\n"
			+ "esaezr rpggiy jey kbzrhu uthus osr xxaiijd qfxlf auhzbx gkigoqw\r\n"
			+ "yfhcj uvgck cds gjhhrg cmempgj yfhcj cjb\r\n" + "yxi voxvtuw unwg jqqm\r\n"
			+ "igvjr ljz rus sru gbjtjt qfeg ztu zjl\r\n" + "leof ocxns hbkoysh hbkoysh leof\r\n"
			+ "hab lyxmf yhh qeks fwhfxki xmbcak okqjii nfgzyg bhtfgdj lpmjn\r\n"
			+ "mgognh tad herere lvwnzx ixwqs zphmuuc etdjz kczsf\r\n" + "mtej rlolsnn zbl uykek dpkan gmz etxtgj\r\n"
			+ "mihuieo emjgbp jgks mihuieo iexrfw mjdnr bvp mcuzea xkbusvi\r\n" + "jvqpj bwt jvqpj bwt gxr\r\n"
			+ "qpnd fpt tpor bibbpcg hmvguez wqc afl ckviua gpi\r\n" + "dntmcg jglm sxtnu sxtnu sxtnu\r\n"
			+ "fzkbptw cbfwo ozvwov wbv gcdd izqo ovwzov lolewo xikqpw\r\n"
			+ "nkxyxzd kpn datf fki werq mwidqx oiibor zizcjph\r\n"
			+ "xvgyxym zor ijoy lvwsf fjuara idvvq rreit mqyyy ctio tzwqqhj rnpee\r\n"
			+ "maqkfpk maqkfpk xukg sfdmnlg xjopvr xjopvr irf\r\n" + "liujcd vnlkouy dxkwc gto vhjvtw\r\n"
			+ "swhqhj cas aupsd swhqhj cas bvbooii jquck dtdm\r\n" + "igh iqicicf ghi pcxt srcrjx gmf gyscphv\r\n"
			+ "drplj drplj wopgpnk wytag wopgpnk\r\n" + "zexe ilcqoh qiefb txkuv lirfzv\r\n"
			+ "ovvpn ovvpn uqeurqx uwzn hgmucj ovvpn sjxulms\r\n" + "rox silka irhsvym kutus otasof tdneav pcagds\r\n"
			+ "mkja omu tyshbfq onp trxs lxa tftbv bnpl djhnc zdqfs muo\r\n"
			+ "tjj rmmqas cbbkxs qio pikk ykyew gxlxt nhsyl ykyew\r\n"
			+ "frcprg njrz oaxcmhc qben pedm ecvtga nzxwpb ior gaklot dpem\r\n"
			+ "zyt kncau spoe qlchg sqys wkpbng yflju qlchg vkve bzadbpa\r\n"
			+ "qtq pkaicl qtq mfkfqvr dnleiq brrjxsx uoyxh pkaicl yvmlug\r\n"
			+ "firwy imtlp ywl qfa dqrbazz ztzb pcsbwhn zesmlag\r\n" + "ivey ivey mtvc mtvc\r\n"
			+ "lhize acwf moa cdeoazd voktshy qmvqq jvmuvk ljfmq tsanygc\r\n"
			+ "xreiqkc aawrovl pofcsg xreiqkc xreiqkc\r\n" + "cjbzvn ozds iniqu sdoz gqmki bablvll krs vjzcbn\r\n"
			+ "izsod htkeqz entxn qtns prpcwu omfnmoy\r\n" + "kwfb tctzda aztctd tadtcz gyt wunbcub ydiwdin xxk\r\n"
			+ "epnl ijcp giq ltfk zjcabve zfksmz epnl giq xxxbsom\r\n"
			+ "ulyukpa mdjsbn dydko uhkdt qms aaaj hustlwu\r\n" + "zlsbu ohx jcwovf egf zlvpqgx qhejm wrywdmw\r\n"
			+ "uhxqrzr mmu kjxcalj unuohiq rri yzngnb ikvlxry mfiym qbksdx\r\n"
			+ "khqciz som yklmm jceb khqciz jspy jceb\r\n" + "ncwggv njvi nqox krtsn lnm\r\n"
			+ "bgtqme xaxcoq qbtgme obqual vorfk baoqul lgrb\r\n"
			+ "jli tsbb nlxjc pkwzmz dlxrj hmho gzguko ilj iyaasm\r\n"
			+ "wlmw grkumg dynwtyo emxhhqr huluk slpqu uhqcmd absmr ufirmwr\r\n"
			+ "pbs pcammxv dplfr tzvmav nccyy blvyq ffhnz bccutq\r\n" + "hgge ghge vxmvz hqxgjdg zab guo gheg\r\n"
			+ "ylj bucoyoq udndc wpgyrbx ueh udndc gxdsdh hdoz wwgqlg\r\n"
			+ "cjdeh gttyqe kdkm ltzd lfeozse quvjq mnwhokm kdv oojxm nxt\r\n"
			+ "mfkzus knqxt saxkqww njx zumsfk sbmcyad cpt agvbuv\r\n"
			+ "tukn vyco yobvsn bzgnn klrnzy kea thzk pxpwq ryfff nxzm\r\n" + "ylbm lxlz lybm lzxl\r\n"
			+ "wgtxoij zad slgsi cvnxfg iomswwl vmx\r\n" + "hkm yinhnkj kmh kwkw kayknck chur styjif yknakck\r\n"
			+ "rtfwhkq rtfwhkq zsf zsf\r\n"
			+ "sldq zlntr ueegiw kajivqc ozcbm ceft snvugom pdyc elppeed nnqrp prwwf\r\n"
			+ "lhk xjonc muc tudag tsafx mmivb dvrjbp qgrew\r\n" + "hnzer fbgqp aazta aazta lxaz lmgv aazta\r\n"
			+ "victgxu victgxu mlpd ummrnbx cazjgnw isxcyp efy zfa cyusj\r\n"
			+ "gyojxo onzq gyojxo uxufp awi ilhl wefwfxr gcjlt tmliynw uxufp pdcnxah\r\n"
			+ "wjwachn xkuhfbp oky oky ybaeqkr rbuix yreoaw wepmye brvon aasb\r\n"
			+ "kiidorw vxtxiqx wtqvbrv efdth isel qbom vcssyc vxtxiqx wtqvbrv riafzsw mqzsj\r\n"
			+ "eurpjd vkhdamt tmfx czeoot hiz ykz lmixzq tfur jhzr\r\n"
			+ "ipuftpj qbll sqkkdw fwncmiv bri oeeh lehd ioh wag\r\n"
			+ "suima nanngc imrmc krq atxdo woy atxdo akev qlr aezco qlr\r\n" + "cfc efwbzck ozkmcxv moczkvx ccf\r\n"
			+ "bnekky iakrk sask uwgnjp iyi rynev bdnas ldh kass\r\n"
			+ "sicmw vvjbvv cap nsumc xgvrlm wsoo uoqdu psykckm\r\n"
			+ "ugg mtr wnzhmmh tjxc ehwnji lwhu mdsckk yvmk enubrqo\r\n"
			+ "grb oxmxz ohu ytetedv ssx apzlppg fdkamm sxofc jdt ynmu wyejok\r\n"
			+ "umoep rbyqm eqfk twqnog cptbbi dragna ngqs ffb cexxnc rbyqm\r\n"
			+ "utizi ormkel wvwur bdx ecelqbv xiccama aag glfvmj\r\n" + "znb rsuqoa uxo svc\r\n"
			+ "obs lbifa cffi catpd\r\n" + "qkxwian ajlzjz wewduzp bbyv qmt fsr qgiu epinp ghmf\r\n"
			+ "hatg bfgmb aght ghat\r\n" + "kuq inp dun cknbun wmwsu drlmmg kyxc bdl\r\n"
			+ "bddybth swdbf jhi fva qpobio bjwm wjaztp jywi\r\n" + "mgckz vhveu zkemhp zdf xtiqqew mlx wazgd\r\n"
			+ "umbjq pya lvvxf jeavij rhrxvew bwjqgpr piz\r\n"
			+ "xaycpwo vjcuc qksc yuixhni sfbfb dydyaq gdfvb tggg xidphvf bpjdrl goskxym\r\n"
			+ "agxfoip gguif wvo agxfoip ntkbaw fbyggy ooft zxih\r\n"
			+ "nzvsu ffwq uxvfbl qrql olhmhom qhdltg ymwz krtndtx olhmhom nfsv krtndtx\r\n"
			+ "qdp jqk ustz xjripzv mnk grnodk pjwdsj uug zqxjqj\r\n"
			+ "mufrcox zunisfs ocvcge acamm xua vor bsde kxr vor kxr orccxx\r\n"
			+ "ncycbp anvcxay bmm wndmeaw oso knmk mmb wamenwd kmkv ppdd\r\n"
			+ "motdcn xzagzwu vuzt utffrn yuqxzrh uvzt ujttq\r\n"
			+ "tauoqy coiy ybesz tauoqy wpmr trquyne ahxbj jzhems dsdy\r\n" + "aczq ypw pgmzz srfn quatjgf\r\n"
			+ "cih ypapk bfxvr euvhkk gugru auhqui\r\n" + "vyf pssgfvy dnhvbfl xpacme dnhvbfl mzdv iynq hcqu\r\n"
			+ "lbzvbu hhxiq hdfyiiz iyzihfd xhqih uzdqyxr\r\n" + "iapbdll vdr cprmrkk vdr dfjqse mlry flpqk vdr\r\n"
			+ "grrfkq xcpxd grrfkq dxc bjpr prvwh swoc swoc\r\n" + "bopo chvwuhf qhd ieesl xey ieesl fnjcbe\r\n"
			+ "kic fyq hsucnu agwyl pzzmd hqksh psw\r\n" + "mxf uau iti lcoz lpg zbu ocre wqlocmh mxf nidqj lcoz\r\n"
			+ "bypmix ptzxgmf xmtzgpf hrvzzq\r\n" + "lbfw zwusma lbfw tuyyy\r\n"
			+ "lrf uej unswvh obgsb npbl zajr kenea uej qnyjcu wzufim qpzkgya\r\n"
			+ "qcrxj llyu kligt hlm ehwtbx dda lgsvhdt xewfcv uikn\r\n"
			+ "nfzjx izqdbq mfbxs imiuc yqxb xlmvix izqdbq eflqfq wku omgtuu izqdbq\r\n"
			+ "lasdwg hiy btzt eefd eyoep icn nnmhg otml rek luixac nyzgn\r\n" + "vekteds utsuxdx utsuxdx vekteds\r\n"
			+ "feyov qrij zbebwg ijrq seplram wttkwm zewbgb kzuhuh\r\n"
			+ "dmkgtv wohgqo ddtqmv zatahx mym hqowog tkmvdg\r\n"
			+ "vhha wjrmuyx kqh vyyrj xzchbi ejsdq orlxg vyyrj dlrc\r\n"
			+ "yetngqn zdtuqox hkarjei fqpsgh eaqwbg zsssog ghb gddqqzr hbg\r\n"
			+ "obldb zsrhz zxp uxphnev mwnbc pfjft fms xwslk vjm fxy\r\n"
			+ "nfij dbfykv ttq gyjgac igxuyqi gtiioqx ilhdex dbfykv uyp bdiwya gqf\r\n" + "pffzruz vogfosh dcs wje\r\n"
			+ "pohhf fhpoh oon yyz\r\n" + "xxuam afwm qxl lnt syyr bwxhhf sozauq shlhfmz kwnn milav ochq\r\n"
			+ "wefcqrt gejw cwerqtf fttf gjew\r\n" + "jfsvnmr osca epwtle pgfif sxom\r\n"
			+ "exlfzmq nakp rgdnx rrcvth vhrrct aajjdrt ryyg dsozd jdqlqj pakn iruv\r\n"
			+ "rmcvo txszcs xxhyxz hbsozk wshkocf rmcvo rcbnt\r\n"
			+ "kitz yjgney yvkymef nauj hmllsgl kyhm kqr pzsu rcf pzsu qpte\r\n"
			+ "cdinpx bfur mkj naz ihkheyr nohhoe\r\n" + "ylris xeqcgup wap bbfih tgfoj\r\n"
			+ "ina gnlnm zyeqhij cudfuf ipufae bvkdzni aat teqsg cudfuf bjokrbl teqsg\r\n" + "aedx edax dnfwq qndwf\r\n"
			+ "rdngdy jde wvgkhto bdvngf mdup eskuvg ezli opibo mppoc mdup zrasc\r\n" + "qcnc iaw grjfsxe gnf gnf\r\n"
			+ "zbjm snznt zelswrk gkhlnx dqxqn qqxnd dmro\r\n"
			+ "zisecvx ztezof uzbq otnrtj qsjzkwm ewvcp rlir bfghlq tgapdr qxmr\r\n" + "ipnqj opjf vabyoe wkwnd\r\n"
			+ "wyf mfqxnrf apm snarf jqu aaghx pwecbv lvghayg\r\n" + "acncv jmmbwlg oiphlm ifuo cvt\r\n"
			+ "pvmb egansnd zmh gcuzzci rrxpslv ubith\r\n" + "uoleptg xbouzn xbmg cfh cpn wpqi xbouzn xtxis sxzpns\r\n"
			+ "rilybri kurbpq vfmjpck tjyogho hfyxad svfofx lfbbhxj khaerfs iqr\r\n"
			+ "seaebgz wlmtkre qguv qguv wlmtkre\r\n" + "sgo edkxya zdqgwtt gxu nibuu rairqoq mzxli dci qsv\r\n"
			+ "tsol mdhzqr rmaqnru ggvcq arbwkn hlkcnj ljkcuof\r\n" + "mmliphp ocup puoc eijjv\r\n"
			+ "gmajqpb ijki ijki kvz\r\n" + "pmqss unhlpcj dlkll nuhlcjp expe tlurzmv nsy vlumtzr tgseozl\r\n"
			+ "gkvaoni hsba hsba viuedv phyoclp fdq phyoclp febld nqfs\r\n"
			+ "rxvdtw abn pntv qrqfzz slsvv abn lrxix mnu npot\r\n"
			+ "ghlfjp woy xwkbmv bkahpkj jve cncvk jvdype fwgvoju yrkwjp gwfvln mvkv\r\n"
			+ "kmluh mie bby fwer chsinb ojglqr nqk mie\r\n"
			+ "yzmiu igkgca ybnsqja jpfejtp yjddy xsosxfi ingx qwuhb emrkwpx idqjmmm\r\n"
			+ "btrllw mphm dkvo ewdl dchcul yah btrllw kmqi mtvgk wtb\r\n"
			+ "hxsgard yuikc lykt tdee adprp gpougod klnzk mzsmlb\r\n" + "hdn znblw ifoblur bwzln dbv\r\n"
			+ "smofpbs vjuyiro llk lfzesga tybu tybu\r\n"
			+ "gffnpug xaup iqiyz fjkpnkz drrk fwyxw lwzfskz gslwpmv vjxylva tbkyo nib\r\n"
			+ "evydmb nhwuiiu fkerq nkgbuyy uclrs ydjgglh xhotwbm riirgzt\r\n"
			+ "bsub eavbt uvd dpzwyt rhn khrbptt xszckc djnfxju axofhat powmso nvdffrv\r\n"
			+ "xtuykl fjz mbikc xpnx hmey fjz fjz\r\n" + "rkls nwdcsyx rkls rkls\r\n"
			+ "tygml untequ ybdfumz nqffbq uipc sove hfnqj\r\n" + "ytecew vven koqn royynd qsn ksl qsn sdw\r\n"
			+ "hknlw qwho whoq oqwh\r\n" + "lzmmtqu qvhyeo cnofuj utpwkjz gnirz yhhu aodbnd\r\n"
			+ "zsr axw kwtzcv tydzo kwtzcv lkxsm\r\n" + "rbjtqe nihifd gvdxd bpxzy rxteky vgcgllv vbbua anygiup rqo\r\n"
			+ "dpd wblfwp wblfwp wblfwp ygahc tqjbaq\r\n" + "gsw gsw pacgj xmrcz zmxhmch xmrcz\r\n"
			+ "pdq rhe xqmq lgpkhg fyffrot ovnqh wle\r\n" + "tbjavke ypzzrj jizx gdxoh icjsat otfh fmygumv\r\n"
			+ "snch nxlgjgp jeyn sxoqfj jtage jtage iuice\r\n" + "rtb coefuj grwg grwg rtb krhqnma vfhgbr\r\n"
			+ "vhegtl btorwxg szcev kbvkx itsk nlzpbed\r\n" + "hiukrf ilzkm yllhh xsgwkdp zyy kjbv\r\n"
			+ "rfcg tdorci zcj wzftlv rfcg rfcg\r\n" + "lgbc lzizat vsno pau nvv vsno bbr lzizat qhtb gwp\r\n"
			+ "sfwnio tcugjk bsfsz ykyfwg ibkap fsrvy mygk kzunawx zyhyh\r\n"
			+ "mpavlh qps bylh lttjkz rqabgk vewb bwev tlzkjt gzrbxga ktmso prpkj\r\n"
			+ "gpf ims ynh ffrs vpa iemp gofh cgbauje\r\n"
			+ "secys qks mcnfhwh drog kqs pajy zoltkw lfihnb myb ioxptu\r\n"
			+ "ytq nrta ouk ajqblf yuwwcd zdy blyoxbw dakk nvgi bzrhzaa\r\n"
			+ "nkoych sufiia xkdvw crtldee zycl qblab egqhr qblab\r\n"
			+ "nllno muxaf vds qjnitmw zkpj wskyhft kmqct xamuzpw qcai cdjtbt kaxv\r\n"
			+ "qzdytpe osr fuw osr qzdytpe whperd rydwdcl knoa\r\n"
			+ "zkdznhd peh duoygr zamrgl irnvj otpe pltpq jdkecg\r\n" + "byzgw rece iigdug ehif tpgje\r\n"
			+ "ccnn foqdran gbctca tefdjxh ntcr rjciii xip xlss crl wvvhzqm twyohf\r\n"
			+ "dqyii milqqc qjgkojp qjgkojp ryde\r\n" + "tdkyj tbrcud tsba vqtmb cjwxnf\r\n"
			+ "hqhmq wemvrce nagig pwnw nagig epg nagig vlsi\r\n"
			+ "tqgvw luoplw hccti npjm rytdruq cylrsun rytdruq vjsbjl rytdruq ppti\r\n"
			+ "itgt tuwc itgt rvp itgt tigns eipl ksmru\r\n" + "pdw wdhtkn nbdbpn wff zhuuipg rvemv qxr\r\n"
			+ "qgkwdq cjilayh ymeks mrpuzai dwgs stfstgz ucvqhb yout oiq\r\n" + "vpxik ypfr qytimvu qms oxbmw ppyfx\r\n"
			+ "fwwidn gdhd pyuexk snsz iwndfw\r\n" + "lfcb sllxjna lfcb hpzahfg mmvgaa svny jhuzd\r\n"
			+ "unyg gicmzd fwc spkciy toyq wjupckd vzzx iuqgka ytqycb pxsufj\r\n"
			+ "goj tnrcml eyizngj txa xrkiw zvu igduz\r\n" + "wek xrrlkna clyof rrlnxak\r\n" + "cjm rmyuku vjom gtf\r\n"
			+ "buk cfae awstd dywgqp hxo wcxvf laihqw xdqfes wdbh qceh uzlwj\r\n"
			+ "sudguo dxwplto rlebdh bkamu dxwplto\r\n" + "crwkyxm yuz kjtdhom crwkyxm\r\n"
			+ "trhc sduorxr aizfryh rsudxor gbyc\r\n" + "pczkyl bptp qnn nxmpwsx udrg hhlb rubtrmx twzodlp xygnht\r\n"
			+ "jmqct cden yfajtkz fevcw sxonbxz sxonbxz qkzkm hhngr fbv\r\n"
			+ "sdsnm mwvicr wypfi cty ndbowr woiz mrauwzd qlno mwvicr\r\n" + "vteyo fng lvr lxytn txpj milg\r\n"
			+ "wjx ahtmgo cgwcaj kaxae fhlvlqf\r\n" + "ezj eetqhzu upwda iiefwlk vyvby\r\n"
			+ "imalvy yeghqe jwcu mvrod cwju\r\n" + "bxnmsa yhfu npsdar tsbri hfuy sirbt oofxmy\r\n"
			+ "fkndt elbjtn vepqtxt elvpf fpelv bzkgag qttexpv prblwb\r\n" + "rmq iqs yvprnyy iezqrzm wlqsrr\r\n"
			+ "yviovq lekxghj oey qwhzj lxknxw qiyovv ksnt jptz\r\n"
			+ "tyrg cifxt hugqf tyrg ffuiv jmax qyw fozfosq ffuiv\r\n"
			+ "nmg rsl jpzazd qbtlf yxqtsj czwmdfd bamge lbjdof uqy jssc\r\n"
			+ "cbx boozjip pwgvzlq rjz kxy kxy hszacok fvsq jhnir cnsba gafz\r\n"
			+ "sbcuxb wfur nnnfqjj fdwg huhe sbcuxb\r\n"
			+ "icwk qelbxs uevp qped zsnhh wpuok wddxsln ftnzupr ruxol cgxjb jbhh\r\n"
			+ "izcp htykj xxmndoq amnspe htykj\r\n" + "vverol oixwlny vqd tvfzu henc gnyrwr\r\n"
			+ "ytxio etytsx choynep zqapo hfjit\r\n" + "lkvgr oyzfa taiqr jok djatvy ckif tmdw oyzfa zroy\r\n"
			+ "jlgpyp kkqysg oqjki hjohoug hbhta muilz zft\r\n"
			+ "sumfyu wftcu bwwdcy lezimwa qwvxv zwh mqyv bmfot aii torcol rnt\r\n"
			+ "tpdj xrw ccsbnh fhptv fwkxjfm dmqaokd bjci\r\n" + "zxi vmf vmf dpyg\r\n"
			+ "sfzxysw lcms bkojtv bkojtv\r\n" + "opywo qll ipkitr mtwp tudrr svhyp huz bxsdpn xomfy\r\n"
			+ "gkod luo qrosbp orbd rpsjzyd rlh gdok tze\r\n" + "nusiuq nusiuq zeys ahufexc\r\n"
			+ "veno jntg avtmtdn qojxru zegdcql odfcetz pgehau\r\n" + "uqun vigjm ykac ozlelj danmji bibugox\r\n"
			+ "rpuozh ajwru rbvuevv uhzsq\r\n" + "iawoe tyb aewio ymf byt inijv ctu fcys micsgzl pbby alt\r\n"
			+ "gktyxp ris mqpfm bkqsfl nrg idbbcxg jhcf\r\n"
			+ "qibt invvv qibt luitx rnm eby hrfbmwl wnap sgkzvb qlwc hrfbmwl\r\n"
			+ "jwkv qecsjbw lycgldd wjvk tjcp dycldgl pzrvr zrlcf kji\r\n" + "nzsrmiq nmhse ilivrk kqv\r\n"
			+ "besmyzi imkgpt iekbjax abxeijk uvzs wwv\r\n" + "jdocl uki ltswp tjkljc ymce iuepze qygqxzs tei lkry\r\n"
			+ "hhyfy gvzd mqksxlq czn afe mesnag eep frwgekg mqksxlq phpy\r\n" + "ehg connnza ekt ddgokw\r\n"
			+ "mpbsoms uzhzl xevww ztt uzhzl\r\n" + "lftybr firc awsud dsxdkk ltf ipjv dtx lcymth\r\n"
			+ "vkcpb gxtxq yioeq fexj xxgqt\r\n" + "srvca fslnnvf nfmkpvt egw wemumq jie vznf dzsjw cukf kcvyir\r\n"
			+ "yxjkl lyjkx jyxlk kgc xtz\r\n" + "tpoe xzov csp leleoqo noyre tdhf cyib sjgtdx raehdw nmcxp\r\n"
			+ "qvt uhznqe bpvos vtq ddlebtd tqv\r\n" + "xlw utsxs gpia rvlvnts elkxr dddihy tnrslvv ibf wlx bxg\r\n"
			+ "cwqnnrt rkkqyf dye yde fzl pthanj\r\n" + "boc rqjenpp xjqte jteqx pvoofc pidqe ruoucy gvnro ognrv\r\n"
			+ "qhalb gnazwc fhl iuti\r\n" + "clnbjfo nnfs nnfs heymvr oarew oarew nxu\r\n"
			+ "lwtrotg hiaxwj ymzbly nvhzjhj zlsaheg nvhzjhj ymzbly\r\n" + "rrvi tsjp tsjp tsjp killji\r\n"
			+ "rpx hiclj cmwq ibhj nfd\r\n" + "pvwymn iebkd xmpw vuhhkap ksw zigzy mzzyyxy rmuh iwwhea cglfq\r\n"
			+ "rlwelgy sffml jin qsdzro xlsty mgqzuu etxjuo emzd jgnoyq tkjuy vfvb\r\n" + "tkctdj hhkuc viskmy obw\r\n"
			+ "zvjkuj akeky ikj jqd hfhzbwe bkc\r\n" + "btev nrdo hcyiuph stf qharfg vpmel mpfz nvs ytgbbc\r\n"
			+ "ieepn ndueuw svmdr tcvumw mceyrn mrjwhyl tbdj mgrgvz\r\n" + "uxrs ckyi xpmqm czzrkl cjp\r\n"
			+ "nlliwd wrqkrkz yjmng nlliwd zirde hcjjn wco ysf mgl\r\n"
			+ "dxti lcahe ommare izlwf ramsfb nzgfvo ijvm fwymrdu bndq\r\n"
			+ "isxy jpvuzu tdduyhw dixp cfa fkzbteg ytoi kepk ysf yqcpi\r\n"
			+ "qmeprfj soqo ncgeor cqsuuj grzy wogxy vyblnbg slvtry vdols kka\r\n"
			+ "ltykfp gtzl olrp gxend vapee deq\r\n" + "emywfbn dbfiut rkt wvwe dbfiut bwffhea yuzcxv gogpicp wvwe\r\n"
			+ "vqvmrp ofbk dlfabd jwllzxk obx vqpwjj umvng tqwis fstxy fstxy\r\n" + "miha zgvyux rmraszo xwf\r\n"
			+ "kjaagk btm kjaagk wkewjrg kjaagk\r\n" + "lbmli aizs omrdr gzktnx asiz ptanzpa xlo ljre ckyb wob\r\n"
			+ "svz dlk rijagg avxmg fkzwhk uro gegm\r\n"
			+ "dzplum temdw jqnm tvxcww bmg tftttpp deuw comxey xfimzjx caluczi nqn\r\n"
			+ "uwvhxa ztkd nlsdyt vihl julkwwv uzch dwakhs\r\n"
			+ "wkhuihh ycrc cxff vzcfhpp uegfd gaok kcnvz lhzogq lwa tyrypvu\r\n"
			+ "idp zmrrzp zmrrzp nktp xsnx rjsxn\r\n" + "eybrnib ivgntl vaxsbpi eybrnib\r\n"
			+ "nzvnq xvbfa pbhwwh ylju runvsj imlx vztesn\r\n"
			+ "nfdohd nfdohd gtevnky pivjyct ihvd fzcsrq lko fmqk\r\n" + "kwpkks ecikxu bcxswlt qvrxm sbcqmh\r\n"
			+ "kdjrmj piuh kdjrmj vnaf gyedkg vptxgm xezssxx zsg qjzpo zsg\r\n"
			+ "oqo sley aqx qmpqb fgmylbj egd zivj kepxizv kuakyn lunbnd\r\n" + "hmcf hmcf xlhgc hmcf cdlm buofnx\r\n"
			+ "onjcj yluonz kzmk phqo phqo phqo\r\n"
			+ "ohaafy efl bnkkjww wwjnyoj dxeaig ywnjjwo slk hrbebw ohlyju elf\r\n"
			+ "msohiqz aunk njki bfktdgi htmyrj mgx\r\n" + "numlzrl rmnlulz glb ltt fhbajz gqxpu\r\n"
			+ "gko hco oai ryq xwy sdqosft spjkiu cxfhg ycwpglh noy rah\r\n"
			+ "btzpjem brpk vqr atxu rhlh rqv jmg fvyus\r\n" + "phmxxgj ejx xje qtk hsb kqt npwj gqt\r\n"
			+ "hujyjp nwmsd ant zipuya lrkahww uwqal vzlo qmbo twkjkse ufivi\r\n"
			+ "zfbnyz fwvh xrnrw usn zin daq iwjzj\r\n" + "yykyg iwypfy hehqnl cjvk cevdrec\r\n"
			+ "gui muuto wsta glqmx gfo rdmbv mxwz gffzt eejpw gion\r\n" + "lpng nduid iqbpu nduid knrqd\r\n"
			+ "xwxn oefpckv gjaua ugaaj gjuaa\r\n" + "qxk aeql trqdmqc crzlinj crzlinj trqdmqc rijcne ewyf\r\n"
			+ "rfv qmbe fvr bmeq\r\n" + "upqyfw lowzq wpen upqyfw gfskbil sljuzh wpen\r\n"
			+ "bdcara qyhx rtaez qyq gbyr\r\n" + "evzls qxtxq clzd svbgqi zxlzgss vtrre fko eebo qjyl\r\n"
			+ "zaapeo kpwhz tygknau nyd pch trp xqe\r\n"
			+ "ypzcafg rnqmbh qtteg sncu ssojhhm zonfym thir xmgheb wqj gpjg ssojhhm\r\n"
			+ "wvcwyn xrf muozyya lasdp xpjgu kpqv zkiihiv ifje cbdlavg xbied hfnaa\r\n"
			+ "qqqb rettz rycukl ihpkhh\r\n" + "dnxzxqv znb znb fbxj azxtezb xvxa\r\n"
			+ "peqkd xlzqkov esgnw ucku hrwpfxd xtd vnig vlmfp ajte qswr kqoj\r\n"
			+ "dpwy oavzkk dwyp ehij upqxgii pydw\r\n" + "amfc hfv xmqa nqvn cal rqmcq oej amqx cla ntxj\r\n"
			+ "hqhhe qkbhwli wmhlcq xaczs peywuo\r\n" + "vcr xfv xfv kymo qpszwzo xfv\r\n"
			+ "nmrbur tswo xbo ljlrzo bmhpgc pev zovkznz lok wbbhtkk\r\n"
			+ "tojj lxqgr rhjavrm ndsdup gdbjwaq cqpnl wfaxivl rfry ryfr udspnd\r\n" + "beffod sknlph amb feobdf\r\n"
			+ "mldgn jxovw yuawcvz kzgzwht rxqhzev fsdnvu vluuo eycoh cugf qjugo\r\n"
			+ "tlnd qcxj ker fdir cgkpo nrqhyq raef uqadf iahy rxx\r\n"
			+ "mhvisju lhmdbs tcxied xeidtc ujry cditex gvqpqm\r\n"
			+ "cgc jazrp crgnna uvuokl uvuokl uoiwl sknmc sknmc\r\n"
			+ "rvbu czwpdit vmlihg spz lfaxxev zslfuto oog dvoksub";

	public static void main(String[] args) throws Exception {
		Solver solver = new Solver();
		String[] splitinput = input.split("\\r\\n");
		int counter = 0;
		for (int i = 0; i < splitinput.length; i++) {
			boolean valid = solver.solveDuplicate(splitinput[i].split(" "));
			if(valid) {
				counter++;
			}
		}
		System.out.println(counter);
		
		counter = 0;
		for (int i = 0; i < splitinput.length; i++) {
			boolean valid = solver.solveAnagram(splitinput[i].split(" "));
			if(valid) {
				counter++;
			}
		}
		System.out.println(counter);
	}
}
